### ISSUE TITLE
Timer up nv9biller.BillerCommunicationsError: Timeout

### ISSUE THREAD

**Issue by rajanlagah** [gmarull/nv9biller#2]
Hey thankyou for the great contribution 
But i am having trouble.
My nv10/nv9 machine give me this error randomly 
I debug and found that 
in ./nv9biller/__init__.py

```
    def _recv(self):
        """ Receive the response of a request.

            Raises:
                BillerCommunicationsError: If there is a communication error.

            Returns:
                bytes: Response payload.
        """

        pkt = b''
        pkt_counter = 0
        state = self._RX_STATE_WAIT_STX
        init = time.time()
        print("time.time() - init")
        print(state)

        while state != self._RX_STATE_FINISHED:
            print(time.time() - init)
            if time.time() - init > ssp.TIMEOUT:
                raise BillerCommunicationsError('Timeout')
```
So state 0-6 take more than 1 sec then it will through error 
Why is this ?
I am not clear what state are doing 
plus If i increase the ssp.TIMEOUT will it be ok ?

**Comment by Lanix87** [comment]
I have the same problem.
What is the solution to the problem?
Please answer.

**Comment by rajanlagah** [comment]
It was issue with multi-threading

**Comment by Lanix87** [comment]
But this code not use multithreading.

**Comment by rajanlagah** [comment]
No i was using running it on some other thread.

**Comment by Lanix87** [comment]
How is connected your nv9? A can't solve my problem. I can't recieve data from device at def _read().

**Comment by rajanlagah** [comment]
U have to manually change the machine mode to something like SSP  also install the software from nv9 website and test on it first. Then it would be lot easy.

**Comment by Lanix87** [comment]
Thank's for answer. It's already configured to SSP, some other program works well, but example.py gives me this error.

  File "/usr/local/lib/python3.7/dist-packages/nv9biller/__init__.py", line 227, in _transmit
    r = self._recv()
  File "/usr/local/lib/python3.7/dist-packages/nv9biller/__init__.py", line 165, in _recv
    raise BillerCommunicationsError('Timeout')
nv9biller.BillerCommunicationsError: Timeout

My nv9 connected via /dev/serial0
Maybe it works on /dev/ttyUSB* only?
